import {useState} from 'react';
export default function Contact(){
 const [prepared,setPrepared]=useState(false);
 const mapsUrl='https://www.google.com/maps/search/?api=1&query=NEODIM%20133%20Rue%20de%20Paris%2095320%20Saint-Leu-la-For%C3%AAt';
 function submit(e){e.preventDefault();setPrepared(true);}
 return <main className="editorial-page contact-page"><section className="page-hero hero-contact"><div><span className="section-kicker light">CONTACT NEODIM</span><h1>Parlons de votre<br/>projet de rénovation.</h1><p>NEODIM accompagne vos travaux de rénovation intérieure, extérieure et maçonnerie depuis Saint-Leu-la-Forêt.</p><a className="btn beige" href={mapsUrl} target="_blank" rel="noreferrer">Ouvrir la fiche Google ↗</a></div></section>
 <section className="section contact-grid"><div className="contact-info"><span className="section-kicker">COORDONNÉES NEODIM</span><h2>Une entreprise locale,<br/>un contact clair.</h2><p>Pour une demande de devis ou un premier échange, retrouvez la fiche publique NEODIM sur Google Maps avec les informations de contact à jour.</p><a className="big-phone" href={mapsUrl} target="_blank" rel="noreferrer">133 Rue de Paris</a><div className="contact-cards"><a href={mapsUrl} target="_blank" rel="noreferrer"><b>Google Maps ↗</b><span>NEODIM · 133 Rue de Paris, 95320 Saint-Leu-la-Forêt.</span></a><a href={mapsUrl} target="_blank" rel="noreferrer"><b>Avis Google ↗</b><span>Consultez les avis, photos et itinéraire directement sur la fiche officielle.</span></a></div><div className="contact-checklist"><h3>Pour préparer votre échange</h3><ul><li>La commune où se situe votre chantier</li><li>Le type de travaux : rénovation, maçonnerie, peinture, plomberie ou extérieur</li><li>Vos photos, dimensions et période souhaitée</li></ul></div></div>
 <form className="contact-form" onSubmit={submit}><span className="section-kicker">DÉCRIVEZ VOTRE BESOIN</span><h2>Votre projet, en quelques mots.</h2><p>Préparez les informations utiles avant de contacter NEODIM via sa fiche Google.</p><div className="form-row"><label>Votre nom<input name="nom" autoComplete="name" required placeholder="Nom et prénom"/></label><label>Téléphone<input name="tel" type="tel" autoComplete="tel" required placeholder="Votre numéro"/></label></div><label>Commune du chantier<input name="commune" autoComplete="address-level2" required placeholder="Ville ou code postal"/></label><label>Les travaux envisagés<select name="type"><option>Rénovation intérieure</option><option>Rénovation extérieure</option><option>Maçonnerie</option><option>Peinture</option><option>Plomberie</option><option>Projet complet</option></select></label><label>Parlez-nous de votre projet<textarea name="message" required rows="5" placeholder="Les travaux souhaités, l’état actuel, les dimensions, vos idées…"/></label><button className="btn dark" type="submit">Préparer ma demande <span aria-hidden="true">→</span></button><small>Ce formulaire vous aide à structurer la demande. Les coordonnées à jour sont disponibles sur la fiche Google NEODIM.</small>{prepared&&<p className="form-feedback" role="status">Votre demande est prête. Ouvrez la fiche Google NEODIM pour utiliser le contact public à jour et transmettre ces informations.</p>}<a className="btn beige contact-google-btn" href={mapsUrl} target="_blank" rel="noreferrer">Contacter via Google ↗</a></form></section>
 <section className="section faq-section"><div className="section-head"><div><span className="section-kicker">AVANT DE NOUS CONTACTER</span><h2>Quelques réponses utiles.</h2></div></div><div className="faq-list"><details><summary>Quels types de projets pouvez-vous étudier ?</summary><p>Rénovation intérieure, rénovation extérieure, maçonnerie, peinture, plomberie et aménagements. Décrivez votre besoin pour que NEODIM puisse vous orienter.</p></details><details><summary>Où se situe l’entreprise ?</summary><p>NEODIM est domiciliée au 133 Rue de Paris, 95320 Saint-Leu-la-Forêt. La fiche Google permet de consulter l’itinéraire et les informations pratiques.</p></details><details><summary>Comment préparer une demande de devis ?</summary><p>Précisez le lieu, la nature des travaux, l’état actuel et, si possible, les dimensions ou photos du chantier.</p></details></div></section>
 </main>;
}
