import {useState} from 'react';
export default function Contact(){
 const [prepared,setPrepared]=useState(false);
 function submit(e){e.preventDefault();const fd=new FormData(e.currentTarget);const body=encodeURIComponent(`Bonjour, je souhaite échanger sur un projet avec D.M. Maçonnerie.\n\nNom : ${fd.get('nom')}\nTéléphone : ${fd.get('tel')}\nCommune : ${fd.get('commune')}\nTravaux : ${fd.get('type')}\n\n${fd.get('message')}`);setPrepared(true);window.location.href=`sms:+33677422064?body=${body}`;}
 return <main className="editorial-page contact-page"><section className="page-hero hero-contact"><div><span className="section-kicker light">FAISONS LE PREMIER PAS</span><h1>Et si on parlait<br/>de votre projet ?</h1><p>Quelques travaux ou une nouvelle idée pour votre maison : commençons par un échange simple.</p><a className="btn beige" href="tel:+33677422064">Appeler le 06 77 42 20 64 ↗</a></div></section>
 <section className="section contact-grid"><div className="contact-info"><span className="section-kicker">UN CONTACT DIRECT</span><h2>À votre écoute,<br/>tout simplement.</h2><p>Présentez-nous votre besoin et la commune du chantier. Nous pourrons discuter des travaux et de la suite à donner à votre projet.</p><a className="big-phone" href="tel:+33677422064">06 77 42 20 64</a><div className="contact-cards"><a href="tel:+33677422064"><b>Par téléphone ↗</b><span>Pour échanger directement sur vos travaux.</span></a><a href="https://www.google.com/maps/search/?api=1&query=8%20impasse%20la%20Capelle%2017700%20Saint-Pierre-d%27Amilly" target="_blank" rel="noreferrer"><b>Saint-Pierre-d’Amilly ↗</b><span>Charente-Maritime et alentours.</span></a></div><div className="contact-checklist"><h3>Pour préparer notre échange</h3><ul><li>La commune où se situe votre chantier</li><li>Le type de travaux et les dimensions approximatives</li><li>Vos envies et la période envisagée</li></ul></div></div>
 <form className="contact-form" onSubmit={submit}><span className="section-kicker">DÉCRIVEZ VOTRE BESOIN</span><h2>Votre projet, en quelques mots.</h2><p>Préparez votre demande par SMS. Vous pourrez la relire dans votre application de messages avant de l’envoyer.</p><div className="form-row"><label>Votre nom<input name="nom" autoComplete="name" required placeholder="Nom et prénom"/></label><label>Téléphone<input name="tel" type="tel" autoComplete="tel" required placeholder="06 00 00 00 00"/></label></div><label>Commune du chantier<input name="commune" autoComplete="address-level2" required placeholder="Ville ou village"/></label><label>Les travaux envisagés<select name="type"><option>Maçonnerie générale</option><option>Rénovation</option><option>Aménagement extérieur</option><option>Travaux sur mesure</option><option>J’ai besoin de conseils</option></select></label><label>Parlez-nous de votre projet<textarea name="message" required rows="5" placeholder="Les travaux souhaités, les dimensions, vos idées…"/></label><button className="btn dark" type="submit">Préparer mon SMS <span aria-hidden="true">→</span></button><small>L’envoi se fait depuis votre application SMS. Vous pouvez aussi nous appeler directement.</small>{prepared&&<p className="form-feedback" role="status">Demande préparée. Si votre application SMS s’est ouverte, relisez votre message puis confirmez l’envoi. Sinon, appelez-nous au 06 77 42 20 64.</p>}</form></section>
 <section className="section faq-section"><div className="section-head"><div><span className="section-kicker">AVANT DE NOUS CONTACTER</span><h2>Quelques réponses utiles.</h2></div></div><div className="faq-list"><details><summary>Quels types de projets pouvez-vous étudier ?</summary><p>Maçonnerie générale, rénovation, extensions, terrasses, allées et aménagements extérieurs. Décrivez votre besoin pour que nous puissions en discuter.</p></details><details><summary>Intervenez-vous dans ma commune ?</summary><p>Nous sommes basés à Saint-Pierre-d’Amilly, en Charente-Maritime. Indiquez-nous la localisation de votre chantier pour confirmer les possibilités d’intervention.</p></details><details><summary>Comment préparer une demande de devis ?</summary><p>Précisez le lieu, la nature des travaux et, si possible, les dimensions approximatives. Un premier échange permet de déterminer les informations et la visite nécessaires.</p></details></div></section>
 </main>;
}
