import {Link} from 'react-router-dom';
import {services,gallery} from '../data.js';
export default function Home(){return <main>
 <section className="home-hero"><div className="hero-bg"/><div className="hero-shade"/><div className="hero-inner"><span className="eyebrow">CONSTRUCTION · RÉNOVATION · AMÉNAGEMENT</span><h1>D.M. Maçonnerie</h1><h2>Un savoir-faire solide<br/>pour vos projets</h2><p>Travaux de maçonnerie générale, rénovation et aménagement.<br/>Des solutions durables, adaptées à vos besoins.</p><div className="hero-actions"><Link className="btn beige" to="/contact">Demander un devis <b>→</b></Link><a className="btn outline" href="tel:+33677422064">☎ 06 77 42 20 64</a></div></div><div className="hero-script">Bâtir<br/>aujourd’hui,<br/>demain</div></section>
 <section className="section services-section"><div className="section-head"><div><span className="section-kicker">NOS SERVICES</span><h2>Des solutions pour tous vos projets</h2></div><p>Un partenaire de confiance<br/>pour vos travaux de maçonnerie.</p></div><div className="service-grid">{services.map(s=><Link key={s.slug} to={`/services/${s.slug}`} className="service-card"><div className="card-image"><img src={s.img} alt={s.title}/></div><div className="card-copy"><h3>{s.title}</h3><p>{s.short}</p><span>En savoir plus <b>→</b></span></div></Link>)}</div></section>
 <section className="about-band"><div className="about-photo"><img src="/realisations-reelles/chantier-dm-05.webp" alt="Réalisation D.M. Maçonnerie"/></div><div className="about-copy"><span className="section-kicker">À PROPOS</span><h2>Une entreprise locale,<br/>passionnée par son métier</h2><p>D.M. Maçonnerie met son savoir-faire au service de vos projets, petits ou grands. Une approche directe, un chantier organisé et une attention particulière portée aux finitions.</p><div className="about-tags"><span>Écoute</span><span>Conseil</span><span>Qualité</span><span>Satisfaction</span></div><Link className="btn dark" to="/a-propos">En savoir plus →</Link></div><div className="about-brand"><img src="/media/logo-mark-dark.svg" alt="D.M. Maçonnerie"/><p>Des fondations solides<br/>pour vos projets de vie</p></div></section>
 <section className="stats-strip"><div><i>◉</i><span><strong>Travail</strong>soigné</span></div><div><i>★</i><span><strong>5/5</strong>avis Google</span></div><div><i>⌖</i><span><strong>Zone d’intervention</strong>Charente-Maritime</span></div><div><i>☎</i><span><strong>06 77 42 20 64</strong>contact direct</span></div></section>
 <section className="section gallery-preview"><div className="section-head"><div><span className="section-kicker">RÉALISATIONS</span><h2>Des projets qui parlent d’eux-mêmes</h2></div><Link to="/realisations">Voir toutes les réalisations →</Link></div><div className="gallery-grid">{gallery.map((g,i)=><Link to="/realisations" className={`gallery-item g${i+1}`} key={i}><img src={g.src} alt={g.title} loading="lazy" decoding="async"/><div><small>{g.tag}</small><b>{g.title}</b></div></Link>)}</div></section>
 <section className="cta-band"><div><span className="section-kicker">VOTRE PROJET</span><h2>Besoin d’un maçon ?</h2><p>Expliquez-nous votre besoin et obtenez un premier échange rapidement.</p></div><div><a className="btn outline-light" href="tel:+33677422064">Appeler maintenant</a><Link className="btn beige" to="/contact">Demander un devis</Link></div></section>
 </main>}


