import {Link} from 'react-router-dom';
import {services,gallery} from '../data.js';
const imgSet=src=>`${src.replace('.webp','-sm.webp')} 560w, ${src} 1100w`;
export default function Home(){return <main>
 <section className="home-hero"><div className="hero-bg"><picture><source media="(max-width: 700px)" srcSet="/media/neodim-hero.webp"/><img src="/media/neodim-hero.webp" alt="Réalisation NEODIM" fetchPriority="high" decoding="async"/></picture></div><div className="hero-shade"/><div className="hero-inner"><span className="eyebrow">NEODIM BTP · RÉNOVATION · CONSTRUCTION</span><h1>Votre maison,<br/>notre savoir-faire.</h1><h2>Des espaces pensés<br/>pour durer.</h2><p>De l’intérieur à l’extérieur, nous donnons une nouvelle vie à vos espaces avec expertise, sérieux et créativité.</p><div className="hero-actions"><Link className="btn beige" to="/contact">Parler de votre projet <b>→</b></Link><Link className="btn outline" to="/realisations">Voir la galerie</Link></div></div><div className="hero-script">Imaginer<br/>l’espace,<br/>autrement</div></section>
 <section className="section services-section"><div className="section-head"><div><span className="section-kicker">NOS SERVICES</span><h2>Des solutions pour tous vos projets</h2></div><p>Un partenaire de confiance<br/>pour vos travaux de maçonnerie.</p></div><div className="service-grid">{services.map(s=><Link key={s.slug} to={`/services/${s.slug}`} className="service-card"><div className="card-image"><img src={s.img} srcSet={imgSet(s.img)} sizes="(max-width: 900px) calc(100vw - 30px), 25vw" alt={s.title} loading="lazy" decoding="async"/></div><div className="card-copy"><h3>{s.title}</h3><p>{s.short}</p><span>En savoir plus <b>→</b></span></div></Link>)}</div></section>
 <section className="about-band"><div className="about-photo"><img src="/realisations-reelles/chantier-dm-05.webp" srcSet="/realisations-reelles/chantier-dm-05-sm.webp 560w, /realisations-reelles/chantier-dm-05.webp 765w" sizes="(max-width: 900px) 100vw, 38vw" alt="Intérieur signé NEODIM" loading="lazy" decoding="async"/></div><div className="about-copy"><span className="section-kicker">À PROPOS DE NEODIM</span><h2>Le beau sens du détail.</h2><p>NEODIM imagine des espaces intérieurs élégants, chaleureux et durables. Une approche sensible, un dialogue simple et une attention particulière portée à chaque matière.</p><div className="about-tags"><span>Écoute</span><span>Harmonie</span><span>Précision</span><span>Durabilité</span></div><Link className="btn dark" to="/a-propos">Découvrir notre approche →</Link></div><div className="about-brand"><img src="/media/logo-nd.png" alt="NEODIM" loading="lazy" decoding="async"/><p>L’espace devient<br/>une signature</p></div></section>
 <section className="stats-strip"><div><i>◉</i><span><strong>Écoute</strong>avant tout</span></div><div><i>★</i><span><strong>Sur mesure</strong>chaque projet</span></div><div><i>⌖</i><span><strong>NEODIM BTP</strong>Saint-Leu-la-Forêt</span></div><div><i>✦</i><span><strong>Google</strong><a href="https://www.google.com/maps/search/?api=1&query=NEODIM%20133%20Rue%20de%20Paris%2095320%20Saint-Leu-la-For%C3%AAt" target="_blank" rel="noreferrer">Voir les avis ↗</a></span></div></section>
 <section className="google-proof"><div className="google-copy"><span className="section-kicker">AVIS GOOGLE</span><h2>Une confiance qui se construit projet après projet.</h2><p>Retrouvez la fiche publique NEODIM sur Google Maps, consultez les avis et découvrez l’itinéraire vers notre adresse.</p><a className="btn dark" href="https://www.google.com/maps/search/?api=1&query=NEODIM%20133%20Rue%20de%20Paris%2095320%20Saint-Leu-la-For%C3%AAt" target="_blank" rel="noreferrer">Voir la fiche Google ↗</a></div><div className="google-card"><div className="google-mark">G</div><div><strong>NEODIM</strong><span>133 Rue de Paris · 95320 Saint-Leu-la-Forêt</span><span className="google-note">Avis et informations vérifiés directement sur Google</span></div><a href="https://www.google.com/maps/search/?api=1&query=NEODIM%20133%20Rue%20de%20Paris%2095320%20Saint-Leu-la-For%C3%AAt" target="_blank" rel="noreferrer">Ouvrir Maps →</a></div></section>
 <section className="section gallery-preview"><div className="section-head"><div><span className="section-kicker">RÉALISATIONS</span><h2>Des projets qui parlent d’eux-mêmes</h2></div><Link to="/realisations">Voir toutes les réalisations →</Link></div><div className="gallery-grid">{gallery.map((g,i)=><Link to="/realisations" className={`gallery-item g${i+1}`} key={i}><img src={g.src} srcSet={imgSet(g.src)} sizes="(max-width: 520px) calc(100vw - 30px), (max-width: 900px) 50vw, 33vw" alt={g.title} loading="lazy" decoding="async"/><div><small>{g.tag}</small><b>{g.title}</b></div></Link>)}</div></section>
 <section className="cta-band"><div><span className="section-kicker">VOTRE PROJET</span><h2>Un intérieur à révéler ?</h2><p>Parlez-nous de vos envies et imaginons ensemble un espace qui vous ressemble.</p></div><div><Link className="btn outline-light" to="/realisations">Voir nos projets</Link><Link className="btn beige" to="/contact">Nous écrire</Link></div></section>
 </main>}


