import {Link} from 'react-router-dom';
import {services} from '../data.js';
const imgSet=src=>`${src.replace('.webp','-sm.webp')} 560w, ${src} 1100w`;
export default function Services(){return <main className="editorial-page services-page">
  <section className="page-hero hero-services"><div><span className="section-kicker light">NOS SAVOIR-FAIRE</span><h1>Des bases solides.<br/>Des projets qui durent.</h1><p>Construire, rénover, aménager : un accompagnement adapté à votre maison et à vos envies.</p><Link className="btn beige" to="/contact">Discuter de mes travaux →</Link></div></section>
  <section className="section"><div className="intro-grid"><div><span className="section-kicker">DU GROS ŒUVRE AUX FINITIONS</span><h2>À chaque projet,<br/>le bon savoir-faire.</h2></div><p>Une extension, une rénovation ou un extérieur à repenser ? Découvrez nos prestations. Nous échangeons avec vous pour définir une solution adaptée à l’existant.</p></div>
  <div className="offer-grid">{services.map((s,i)=><article className="offer-card" key={s.slug}><div className="offer-photo"><img src={s.img} srcSet={imgSet(s.img)} sizes="(max-width: 900px) calc(100vw - 30px), 50vw" alt={s.title} loading="lazy" decoding="async"/><span>0{i+1}</span></div><div className="offer-copy"><h3>{s.title}</h3><p>{s.desc}</p><ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul><Link to={`/services/${s.slug}`}>Découvrir la prestation <span aria-hidden="true">↗</span></Link></div></article>)}</div></section>
  <section className="method-band"><div className="section"><div className="section-head"><div><span className="section-kicker">COMMENT ÇA SE PASSE ?</span><h2>Votre chantier, étape par étape.</h2></div><Link to="/contact">Parlons de votre projet →</Link></div><div className="method-grid">{[['Échanger','Vous nous présentez vos idées, le lieu et vos priorités.'],['Observer','Nous étudions l’existant et les contraintes du chantier.'],['Définir','Les travaux et le devis sont précisés avant de commencer.'],['Réaliser','Place aux travaux, avec une attention portée aux finitions.']].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="cta-band"><div><span className="section-kicker light">VOTRE PROJET COMMENCE ICI</span><h2>Vous avez une idée en tête ?</h2><p>Faisons le point sur les possibilités de votre chantier.</p></div><Link className="btn beige" to="/contact">Parler de mon projet →</Link></section>
</main>}
